"""Update Student model with new fields and constraints

Revision ID: b374e70457a3
Revises: 7b563339cbf0
Create Date: 2025-05-22 21:34:56.157510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b374e70457a3'
down_revision = '7b563339cbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user') # Закомментировано, так как таблицы уже нет
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=32), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint("uq_student_email", ['email'])
        batch_op.drop_column('phone')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint("uq_student_email", type_='unique')
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('date_of_birth')

    # op.create_table('user', # Закомментировано
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    # sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    # sa.Column('role', sa.VARCHAR(length=16), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
    # ### end Alembic commands ###
